<?php
/*
 * CredofasterPartnerApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace CredofasterPartnerApiLib;

/**
 * Environments available for API
 */
class Environments
{
    /**
     * Live Environment
     */
    const PRODUCTION = "production";

    /**
     * For Test Purpose
     */
    const SANDBOX = "Sandbox";

    /**
     * Development
     */
    const DEVELOPMENT = "Development";
}
